### ISSUE TITLE
Update the app to use the new python services

### ISSUE THREAD

**Issue by claudiughioc** [initiativaromania/HartaBanilorPublici#3]
As the python server is changed, it might offer different API services (functions) with different parameters. Make sure that the current functionality of HBP is still in place with the new python API.

**Comment by claudiughioc** [comment]
Initially we will load all the public institutions when the app starts (there should be a couple of thousands) and we'll have to see if the app lags when it loads all of them.

**Comment by arw357** [comment]
For this you should provide a call and response definition. For each method that already exists at least in the beginning.
