### ISSUE TITLE
Update the Public Institution and Company activities to browse through contracts

### ISSUE THREAD

**Issue by claudiughioc** [initiativaromania/HartaBanilorPublici#8]
When displaying a Contract we should be able to browse through the previous and following contracts, without returning to the previous activity and selecting the next contract from the list.

**Comment by arw357** [comment]
Working on this - after selecting a contract from the list - swype left or right to go to the next or previous contract in the list.

**Comment by claudiughioc** [comment]
Yes, wither swipe or a next/previous button
