### ISSUE TITLE
Decide whether to keep or discard the "Around you" section

### ISSUE THREAD

**Issue by claudiughioc** [initiativaromania/HartaBanilorPublici#9]
When displaying all the contracts on the Google Map we can see a translucent circle with the center positioned at our location. The size of this circle can be changed using the side bar at the bottom of the screen. When moving the side bar, there is a counter on top of the side-bar, which displays dynamically the total value of the contracts in that circle. Also in the "Contracts" section, we can see all the contracts in the circle listed in the "Around you" subsection.
I think this is not really useful, or maybe we could find a more attractive way to display the contracts around the user. Let's discuss this here.

**Comment by adrim** [comment]
Let's keep it for now.
Note: When location is disabled, total sum is 0. It should be the sum of the contracts in the default area.
